### ISSUE TITLE
Can't start development server after cloning

### ISSUE THREAD

**Issue by Musaiyib** [adrianhajdin/project_modern_ui_ux_restaurant#16]
PS C:\Users\The Only Supplier\Desktop\react\restaurant> yarn add postcss
yarn add v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["postcss@^8.4.21"] is trying to unpack in the same destination "C:\\Users\\The Only Supplier\\AppData\\Local\\Yarn\\Cache\\v6\\npm-postcss-8.4.21-c639b719a57efc3187b13a1d765675485f4134f4-integrity\\node_modules\\postcss" as pattern ["postcss@^8.1.0"]. This could result in non-deterministic behavior, skipping.
[3/4] Linking dependencies...
warning " > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\The Only Supplier\Desktop\react\restaurant\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by gitXpro** [comment]
when you clone a project you should follow this 

# Newer Version of Node Troubleshooting

`Run:`

```
npm install -g npm-check-updates
```

`Then:`
```
ncu -u
```

`Then:`

```
npm install
npm install --force
npm install --legacy-peer-deps    (recommanded)
```

`Then:`

```
npm start
```

**Comment by roudlek** [comment]
> Try this
> # Newer Version of Node Troubleshooting
> 
> `Run:`
> 
> ```
> npm install -g npm-check-updates
> ```
> 
> `Then:`
> 
> ```
> ncu -u
> ```
> 
> `Then:`
> 
> ```
> npm install
> npm install --force
> npm install --legacy-peer-deps    (recommanded)
> ```
> 
> `Then:`
> 
> ```
> npm start
> ```

@supercluster-x thanks man it works
